### ISSUE TITLE
When `operation` field is not set for filters based `StringFilter`, connection are closed prematurely

### ISSUE THREAD

**Issue by haga-rak** [haga-rak/fluxzy.core#207]
This is a example of yaml rule that leads to this bug:

```
filter:
  typeKind: HostFilter
  pattern: example.com
actions:
  - typekind: NoOpAction
```
