### ISSUE TITLE
Optimization of rule yaml definitions to avoid repetition

### ISSUE THREAD

**Issue by gokanil** [haga-rak/fluxzy.core#403]
I am trying to create a series of rules, and currently, I've come up with the following structure:

```
rules:
  - filter:
      typeKind: AbsoluteUriFilter
      pattern: ^.*test1\.xyz\/.*.mp4
      operation: Regex
    action:
      typeKind: AbortAction

  - filter:
      typeKind: AbsoluteUriFilter
      pattern: ^.*test2\.com\/.*
      operation: Regex
    action:
      typeKind: AbortAction

  - filter:
      typeKind: AbsoluteUriFilter
      pattern: ^.*test3\.com\/xxx.*
      operation: Regex
    action:
      typeKind: AbortAction
```

If I want to block thousands of requests, this leads to a lot of repetitive values. Is it possible to simplify it to something like this instead?

```
  - filter:
      typeKind: AbsoluteUriFilter
      pattern: ^.*test1\.xyz\/.*.mp4
      pattern: ^.*test2\.com\/.*
      pattern: ^.*test3\.com\/xxx.*
      operation: Regex
    action:
      typeKind: AbortAction
```

Additional Question:
How can I convert the following approach into a YAML file?

```
fluxzySetting.ConfigureRule().WhenUriMatch("https://test.com", StringSelectorOperation.StartsWith) 
    .TransformResponse((_, originalContent) => Task.FromResult(originalContent.Replace("xxx", "")));
```
