### ISSUE TITLE
My FilterCollection Issue

### ISSUE THREAD

**Issue by gokanil** [haga-rak/fluxzy.core#419]
The following filter works:
```
rules:
  - filter:
      typeKind: FilterCollection
      operation: And
      children:
      - typeKind: HostFilter
        pattern: googleusercontent.com
        operation: Exact
    action:
      typeKind: AbortAction
```

This one also works:
```
rules:
  - filter:
      typeKind: FilterCollection
      operation: And
      children:
      - typeKind: AbsoluteUriFilter
        operation: EndsWith
        pattern: gif
    action:
      typeKind: AbortAction
```

But this one does not work — why?
```
rules:
  - filter:
      typeKind: FilterCollection
      operation: And
      children:
      - typeKind: HostFilter
        pattern: googleusercontent.com
        operation: Exact
      - typeKind: AbsoluteUriFilter
        operation: EndsWith
        pattern: gif
    action:
      typeKind: AbortAction
```

Additional Question
Is there a logic error in this rule? I couldn't get it to work:
```
rules:
  - filter:
      typeKind: FilterCollection
      operation: And
      children:
      - typeKind: ResponseHeaderFilter
        headerName: Content-Type
        operation: Contains
        pattern: gif
    action:
      typeKind: AbortAction
```

**Comment by gokanil** [comment]
I found a mistake in my rule — it's working now.
```
rules:
  - filter:
      typeKind: FilterCollection
      operation: And
      children:
      - typeKind: HostFilter
        pattern: blogger.googleusercontent.com
        operation: Exact
      - typeKind: AbsoluteUriFilter
        operation: EndsWith
        pattern: gif
    action:
      typeKind: AbortAction
```

We can close the issue once I find an answer to my additional question.
